SELECT INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME=N'Movies' 
AND CONSTRAINT_NAME =
(
SELECT CONSTRAINT_NAME 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME=N'Movies' AND CONSTRAINT_TYPE=N'PRIMARY KEY'
);

--AND CONSTRAINT_NAME LIKE N'PK_%'
;

--SELECT *
--FROM INFORMATION_SCHEMA.COLUMNS;